[package]
name = "cr-guest-sys"
version = "0.1.0"
authors = ["Robert G. Jakabosky <rjakabosky+neopallium@neoawareness.com>"]
edition = "2018"
links = "cr-guest"
build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0"
